force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Genres__c.field-meta.xml
<CustomField>
    <fullName>Genres__c</fullName>
    <label>Genres</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalGenres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Album__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>ReleaseDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Spotify_Request_Log__e/Spotify_Request_Log__e.object-meta.xml
<CustomObject>
    <label>Spotify_Request_Log</label>
    <pluralLabel>Spotify_Request_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spotify_Request_Log__e/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/GlobalGenres.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&quot;acoustic&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;afrobeat&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;alt-rock&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;alternative&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;ambient&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;anime&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;black-metal&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;bluegrass&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;blues&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;bossanova&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;brazil&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;breakbeat&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;british&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;cantopop&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;chicago-house&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;children&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;chill&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;classical&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;club&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;comedy&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;country&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;dance&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;dancehall&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;death-metal&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;deep-house&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;detroit-techno&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;disco&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;disney&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;drum-and-bass&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;dub&quot;,</fullName>
    </customValue>
    <masterLabel>Global Genres</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/service/SyncAlbum.cls
public class SyncAlbum {

    @TestVisible
    private static Database.SaveResult errorEventResult;
    public static void syncAlbum(List<ClientCredential__c> credentials) {

        try {
            Map<String, Album__c> recordsToUpsertAlbumsMap = new Map<String, Album__c>();

            for (ClientCredential__c cred : credentials) {

                HttpResponse token = SpotifyApiHttpClient.getToken(
                    cred.ClientId__c,
                    cred.ClientSecret__c
                );

                if (token.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                continue;

                List<SimplefieldAlbumsObject> albumsRes = getSimplefieldAlbumsObjectList(token, cred);

                for (SimplefieldAlbumsObject album : albumsRes) {

                    if (!recordsToUpsertAlbumsMap.containsKey(album.id)) {

                        Album__c albumRecord = new Album__c(
                            Name = album.name,
                            Genres__c = String.join(album.genres, ';'),
                            Popularity__c = album.popularity,
                            ReleaseDate__c = album.release_date,
                            SpotifyId__c = album.id,
                            url__c = album.external_urls?.spotify
                        );

                        recordsToUpsertAlbumsMap.put(album.id, albumRecord);
                    }
                }
            }

            if (!recordsToUpsertAlbumsMap.isEmpty()) {
                upsert recordsToUpsertAlbumsMap.values() SpotifyId__c;
            }
        } catch (Exception error) {
            Spotify_Request_Log__e errorEvent = new Spotify_Request_Log__e(
                ApexError__c = error.getMessage()
            );
            errorEventResult = EventBus.publish(errorEvent);
        } 
    }

    private static List<SimplefieldAlbumsObject> getSimplefieldAlbumsObjectList(HttpResponse token, ClientCredential__c cred) {

        List<String> albumIds = new List<String>();
        PlaylistResponse playlists;
        Integer cont = 0;
        TokenResponse tokenRes = TokenResponse.parse(token.getBody());

        do {

            HttpResponse playlistsRes = SpotifyApiHttpClient.getPlaylist(
                tokenRes.access_token,
                cred.SpotifyUserId__c,
                cont 
            );

            if (playlistsRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE) 
            continue;

            playlists = PlaylistResponse.parse(playlistsRes.getBody());

            for (SimplefiedPlaylistObject playlist : playlists.items) {

                HttpResponse trackRes = SpotifyApiHttpClient.getTrack(
                    tokenRes.access_token,
                    playlist.id
                );

                if (trackRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE) 
                continue;

                TrackResponse tracks = TrackResponse.parse(trackRes.getBody());
                albumIds.addAll(tracks.getAlbumIds());
            }
            cont += playlists.items.size();

        } while (cont < playlists.total);

        return getAlbumsList(albumIds, tokenRes.access_token);
    }

    private static List<SimplefieldAlbumsObject> getAlbumsList(List<String> albumIds, String token) {

        Set<String> albumsToProcess = new Set<String>();
        List<HttpResponse> albumListResponse = new List<HttpResponse>();
        List<SimplefieldAlbumsObject> albumsResult = new List<SimplefieldAlbumsObject>();

        for (Integer i = 0; i < albumIds.size(); i ++) {

            albumsToProcess.add(albumIds[i]);

            if (albumsToProcess.size() == SpotifyApiHttpClient.MAXIMUN_SIZE || albumIds.size() == i + 1) {

                albumListResponse.add(SpotifyApiHttpClient.getAlbum(token, albumsToProcess));
                albumsToProcess.clear();
            }
        }

        for (HttpResponse albums : albumListResponse) {

            if (albums.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
            continue;

            AlbumResponse Result = AlbumResponse.parse(albums.getBody());
            albumsResult.addAll(Result.albums);
        }

        return albumsResult;
    }
}