force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artist__c/Artist__c.object-meta.xml
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Album__c.field-meta.xml
<CustomField>
    <fullName>Album__c</fullName>
    <label>Album</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/jobs/DeleteLastRecordsNotUpdated.cls
public class DeleteLastRecordsNotUpdated implements Database.Batchable<SObject>{

    public  Iterable<SObject> start(Database.BatchableContext bc) {

        List<SObject> listObjects = new List<SObject>();
        listObjects.addAll([SELECT Id FROM Track__c WHERE LastModifiedDate < LAST_MONTH]);
        listObjects.addAll([SELECT Id FROM Album__c WHERE LastModifiedDate < LAST_MONTH]);
        listObjects.addAll([SELECT Id FROM Playlist__c WHERE LastModifiedDate < LAST_MONTH]);
        listObjects.addAll([SELECT Id FROM Artist__c WHERE LastModifiedDate < LAST_MONTH]);

        return listObjects;
    }

    public void execute(Database.BatchableContext bc, List<SObject> listObjects) {
        delete listObjects;
    }

    public  void finish(Database.BatchableContext bc) {}
}