force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artist__c/Artist__c.object-meta.xml
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Album__c.field-meta.xml
<CustomField>
    <fullName>Album__c</fullName>
    <label>Album</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/jobs/test/DeleteLastRecordsNotUpdatedTest.cls
@IsTest
public class DeleteLastRecordsNotUpdatedTest {
    @IsTest
    static void deleteLastRecordsNotUpdatedTest() {
        //Arrange
        Album__c album = new Album__c(
            LastModifiedDate = System.now().addMonths(-2), 
            CreatedDate = System.now().addMonths(-3)
        );
        insert album;
        Track__c track = new Track__c(
            Album__c = album.id, 
            LastModifiedDate = System.now().addMonths(-2),
            CreatedDate = System.now().addMonths(-3)
        );
        insert track;
        Playlist__c playlist = new Playlist__c(
            LastModifiedDate = System.now().addMonths(-2),
            CreatedDate = System.now().addMonths(-3)
        );
        insert playlist;
        Artist__c artist = new Artist__c(
            LastModifiedDate = System.now().addMonths(-2), 
            CreatedDate = System.now().addMonths(-3)
        );
        insert artist;
        //Act
        Test.startTest();
        DeleteLastRecordsNotUpdated batch = new DeleteLastRecordsNotUpdated(); 
        Database.executeBatch(batch);
        Test.stopTest();
        //assert
        
        List<Track__c> TrackAfterBatch = [SELECT Id FROM Track__c WHERE Id =: track.Id];
        List<Playlist__c> PlaylistAfterBatch = [SELECT Id FROM Playlist__c WHERE Id =: playlist.Id];
        List<Artist__c> ArtistAfterBatch = [SELECT Id FROM Artist__c WHERE Id =: artist.Id];
        
        assert.isTrue(TrackAfterBatch.isEmpty(), 'The track list is not empty after the batch is run.');
        assert.isTrue(PlaylistAfterBatch.isEmpty(), 'The playlist list is not empty after the batch is run.');
        assert.isTrue(ArtistAfterBatch.isEmpty(), 'The  artist list is not empty after the batch is run.');
    }
}