force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Album__c.field-meta.xml
<CustomField>
    <fullName>Album__c</fullName>
    <label>Album</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/DiscNumber__c.field-meta.xml
<CustomField>
    <fullName>DiscNumber__c</fullName>
    <label>Disc Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/DurationMs__c.field-meta.xml
<CustomField>
    <fullName>DurationMs__c</fullName>
    <label>Duration Ms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Explicit__c.field-meta.xml
<CustomField>
    <fullName>Explicit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the track has explicit lyrics</description>
    <label>Explicit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Markets__c.field-meta.xml
<CustomField>
    <fullName>Markets__c</fullName>
    <label>Markets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalMarkeds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Track__c/fields/Popularity__c.field-meta.xml
<CustomField>
    <fullName>Popularity__c</fullName>
    <label>Popularity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/SpotifyId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyId__c</fullName>
    <externalId>true</externalId>
    <label>Spotify Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/GlobalMarkeds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&quot;AD&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AE&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AG&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AL&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AM&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AO&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AR&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AT&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AU&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;AZ&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BA&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BB&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BD&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BE&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BF&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BG&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BH&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BI&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BJ&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BN&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BO&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BR&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BS&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BT&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BW&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BY&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;BZ&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;CA&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;CD&quot;,</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;CG&quot;,</fullName>
    </customValue>
    <masterLabel>Global Markeds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/service/SyncTrack.cls
public class SyncTrack {

    public static void syncTrack(List<ClientCredential__c> credentials) {
         
        Map<String, Track__c> recordsToUpsertTracksMap = new Map<String, Track__c>();

        for (ClientCredential__c cred : credentials) {

            HttpResponse token = SpotifyApiHttpClient.getToken(
                cred.ClientId__c,
                cred.ClientSecret__c
            );

            if (token.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
            continue;

            HttpResponse tracksRes = getTracksResponse(token, cred);

            if (tracksRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
            continue;

            TrackResponse tracksResult = TrackResponse.parse(tracksRes.getBody());

            for (ItemTrack item : tracksResult.items) {

                SimplefieldTracksObject track = item.track;

                if (!recordsToUpsertTracksMap.containsKey(track.id)) {

                    Track__c trackRecord = new Track__c(
                        //Markets__c = String.join(track.available_markets, ';'),
                        Album__r = new Album__c(SpotifyId__c = track.album.id),
                        DiscNumber__c = track.disc_number,
                        DurationMs__c = track.duration_ms,
                        Explicit__c = track.explicit,
                        url__c = track.external_urls?.spotify,
                        SpotifyId__c = track.id,
                        Name = track.name,
                        Popularity__c = track.popularity
                    );

                    recordsToUpsertTracksMap.put(track.id, trackRecord);
                }
            }
        }
        
        if (!recordsToUpsertTracksMap.isEmpty()) {
            upsert recordsToUpsertTracksMap.values() SpotifyId__c;
        }
    }

    private static HttpResponse getTracksResponse(HttpResponse token, ClientCredential__c cred) {

        HttpResponse trackRes;
        PlaylistResponse playlists;
        Integer cont = 0;
        TokenResponse tokenRes = TokenResponse.parse(token.getBody());
        
        do {

            HttpResponse playlistsRes = SpotifyApiHttpClient.getPlaylist(
                tokenRes.access_token,
                cred.SpotifyUserId__c,
                cont 
            );

            if (playlistsRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE) 
            continue;

            playlists = PlaylistResponse.parse(playlistsRes.getBody());

            for (SimplefiedPlaylistObject playlist : playlists.items) {

                trackRes = SpotifyApiHttpClient.getTrack(
                    tokenRes.access_token,
                    playlist.id
                );
            }
            cont += playlists.items.size();

        } while (cont < playlists.total);
        
        return trackRes;
    }
}