force-app/main/default/objects/Artist__c/Artist__c.object-meta.xml
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artist__c/fields/Popularity__c.field-meta.xml
<CustomField>
    <fullName>Popularity__c</fullName>
    <label>Popularity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Spotify_Request_Log__e/Spotify_Request_Log__e.object-meta.xml
<CustomObject>
    <label>Spotify_Request_Log</label>
    <pluralLabel>Spotify_Request_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spotify_Request_Log__e/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/service/SyncArtist.cls
public class SyncArtist {

    @TestVisible
    private static Database.SaveResult errorEventResult;
    public static void syncArtist(List<ClientCredential__c> credentials) {
        
        try {
            Map<String, Artist__c> recordsToUpsertArtistsMap = new Map<String, Artist__c>();

            for (ClientCredential__c cred : credentials) {

                HttpResponse token = SpotifyApiHttpClient.getToken(
                    cred.ClientId__c,
                    cred.ClientSecret__c
                );

                if (token.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                continue;

                List<SimplefieldArtistObject> artists = getArtistsList(
                    TokenResponse.parse(token.getBody()).access_token,
                    cred.SpotifyUserId__c);

                for (SimplefieldArtistObject artist : artists) {

                    if (!recordsToUpsertArtistsMap.containsKey(artist.id)) {

                        Artist__c artistRecord = new Artist__c(
                            url__c = artist.external_urls?.spotify,
                            Followers__c = artist.followers?.total,
                            //Genres__c = String.join(artist.genres, ';'),
                            SpotifyId__c = artist.id,
                            Name = artist.name,
                            Popularity__c = artist.popularity
                        );

                        recordsToUpsertArtistsMap.put(artist.id, artistRecord);
                    }
                }
            }

            if (!recordsToUpsertArtistsMap.isEmpty()) {
                upsert recordsToUpsertArtistsMap.values() SpotifyId__c;
            }

        } catch (Exception error) {
            Spotify_Request_Log__e errorEvent = new Spotify_Request_Log__e(
                ApexError__c = error.getMessage()
            );  
            errorEventResult = EventBus.publish(errorEvent);     
        }
    }

    private static List<SimplefieldArtistObject> getArtistsList(String token, String spotifyUserId) {

        List<String> artistIds = getArtistIds(token, spotifyUserId);
        Set<String> artistsToProcess = new Set<String>();
        List<SimplefieldArtistObject> result = new List<SimplefieldArtistObject>();

        for (Integer i = 0; i < artistIds.size(); i ++) {

            artistsToProcess.add(artistIds[i]);

            if (artistsToProcess.size() == SpotifyApiHttpClient.MAXIMUM_ARTIST_REQUEST_SIZE || artistIds.size() == i + 1) {

                HttpResponse response = SpotifyApiHttpClient.getArtist(token, artistsToProcess);

                if (response.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                continue;

                result.addAll(ArtistResponse.parse(response.getBody()).artists);
                artistsToProcess.clear();
            }
        }

        return result;
    }

    private static List<String> getArtistIds(String token, String spotifyUserId) {

        PlaylistResponse playlists;
        Integer cont = 0;
        List<String> result = new List<String>();

        do {

            HttpResponse playlistsRes = SpotifyApiHttpClient.getPlaylist(token, spotifyUserId, cont);

            if (playlistsRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
            continue;

            playlists = PlaylistResponse.parse(playlistsRes.getBody());

            for (SimplefiedPlaylistObject playlist : playlists.items) {
                //cambiar nombre .getplaylisTracks
                HttpResponse trackRes = SpotifyApiHttpClient.getPlaylistTracks(token, playlist.id);
                
                if (trackRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                continue;

                TrackResponse tracks = TrackResponse.parse(trackRes.getBody());
                                result.addAll(tracks.getArtistIds());
            }
            cont += playlists.items.size();

        } while (cont < playlists.total);

        return result;
    }
}