force-app/main/default/objects/Artist__c/Artist__c.object-meta.xml
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/SpotifyId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyId__c</fullName>
    <externalId>true</externalId>
    <label>Spotify Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TrackArtist__c/TrackArtist__c.object-meta.xml
<CustomObject>
    <label>TrackArtist</label>
    <nameField>
        <label>TrackArtist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrackArtists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TrackArtist__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <referenceTo>Artist__c</referenceTo>
    <relationshipLabel>TrackArtists</relationshipLabel>
    <relationshipName>TrackArtists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TrackArtist__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>TrackArtists</relationshipLabel>
    <relationshipName>TrackArtists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/entities/SimplefieldTracksObject.cls
public class SimplefieldTracksObject {

    public SimplefieldAlbumsObject album;
    public List<SimplefieldArtistObject> artists;
    public List<String> available_markets;
    public Integer disc_number;
    public Integer duration_ms;
    public Boolean explicit;
    public ExternalUrls external_urls;
    public String id;
    public String name;
    public Integer popularity;
    public String preview_url;

    public static SimplefieldTracksObject parse(String jsonBody) {
        return (SimplefieldTracksObject) JSON.deserialize(jsonBody, SimplefieldTracksObject.class);
    }

    public List<TrackArtist__c> getTrackArtist() {

        List<TrackArtist__c> result = new List<TrackArtist__c>();

        for (SimplefieldArtistObject artist : this.artists) {

            TrackArtist__c trackArtistRecord = new TrackArtist__c(
                Track__r = new Track__c(
                    SpotifyId__c = id
                ),
                Artist__r = new Artist__c(
                    SpotifyId__c = artist.id
                )
            );
            result.add(trackArtistRecord); 
        }

        return result;
    }
}