force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientCredential</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spotify_Request_Log__e/Spotify_Request_Log__e.object-meta.xml
<CustomObject>
    <label>Spotify_Request_Log</label>
    <pluralLabel>Spotify_Request_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spotify_Request_Log__e/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/TrackPreviewController.cls
public class TrackPreviewController {

    @TestVisible
    private static Database.SaveResult errorEventResult;
    @AuraEnabled(cacheable=true)
    public static String findTrackPreviewUrl(String recordSpotifyId) {

        try { 
            String resultUrl;
            ClientCredential__c cred = [
                SELECT 
                    ClientId__c, 
                    ClientSecret__c, 
                    SpotifyUserId__c
                FROM 
                    ClientCredential__c 
                WHERE 
                    User__c =:UserInfo.getUserId()
            ];

            HttpResponse token = SpotifyApiHttpClient.getToken(
                cred.ClientId__c,
                cred.ClientSecret__c
            );

            if (token.getStatusCode() == SpotifyApiHttpClient.SUCCESS_STATUS_CODE) {

                TokenResponse tokenResult = TokenResponse.parse(token.getBody());

                HttpResponse response = SpotifyApiHttpClient.requestBase(
                    'https://api.spotify.com/v1/tracks/',
                    recordSpotifyId,
                    tokenResult.access_token
                );

                if (response.getStatusCode() == SpotifyApiHttpClient.SUCCESS_STATUS_CODE) {

                    SimplefieldTracksObject trackResult = SimplefieldTracksObject.parse(response.getBody());
                    resultUrl = trackResult.preview_url;
                }
            }

            return resultUrl;

        } catch (Exception error) {
            Spotify_Request_Log__e errorEvent = new Spotify_Request_Log__e(
                ApexError__c = error.getMessage()
		    );  
            errorEventResult = EventBus.publish(errorEvent);
            
            throw new AuraHandledException('COULD NOT GET URL: ' + error.getMessage());
        }
    }
}