force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientCredential</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/controllers/tests/trackPreviewControllerTest.cls
@IsTest
private class trackPreviewControllerTest {

  @IsTest
	static void itShouldReturnSpotifyTrackPreviewUrl() {
		// prepare data
		Test.setMock(HttpCalloutMock.class, new Mock());
		ClientCredential__c newCretentials = new ClientCredential__c(
			User__c = UserInfo.getUserId(),
			ClientId__c = 'ClientId__c',
			ClientSecret__c = 'ClientSecret__c',
			SpotifyUserId__c = 'SpotifyUserId__c'
		);
		insert newCretentials;
		// test
		Test.startTest();
		String url = trackPreviewController.findTrackPreviewUrl('123456'); 
		Test.stopTest();
		// assert
        String.isNotBlank(url);
	}

	private class Mock implements HttpCalloutMock {

		public HTTPResponse respond(HTTPRequest request) {
 
			HttpResponse response = new HttpResponse();
			response.setStatusCode(SpotifyApiHttpClient.SUCCESS_STATUS_CODE);
			response.setHeader('Content-Type', 'application/json');

			if (request.getEndpoint().contains(SpotifyApiHttpClient.BASE_TOKEN_ENDPOINT + '/token')) {
				TokenResponse token = new TokenResponse();
				token.access_token = '1111';
				response.setBody(JSON.serialize(token));

			} else {
				response.setBody('{"preview_url":"this is the url"}');
            }

			return response;  
		}
	}
}