force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/fields/public__c.field-meta.xml
<CustomField>
    <fullName>public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Playlist__c/fields/SpotifyId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyId__c</fullName>
    <externalId>true</externalId>
    <label>Spotify Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlaylistTrack__c/PlaylistTrack__c.object-meta.xml
<CustomObject>
    <label>Playlist Track</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>PlaylistTrack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlaylistTracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlaylistTrack__c/fields/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <label>Playlist</label>
    <referenceTo>Playlist__c</referenceTo>
    <relationshipName>MyPlaylists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PlaylistTrack__c/fields/PlaylistTrack__c.field-meta.xml
<CustomField>
    <fullName>PlaylistTrack__c</fullName>
    <externalId>true</externalId>
    <label>Playlist Track</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PlaylistTrack__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipName>MyPlaylists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Spotify_Request_Log__e/Spotify_Request_Log__e.object-meta.xml
<CustomObject>
    <label>Spotify_Request_Log</label>
    <pluralLabel>Spotify_Request_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spotify_Request_Log__e/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/SpotifyId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyId__c</fullName>
    <externalId>true</externalId>
    <label>Spotify Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/service/SyncPlaylist.cls
public class SyncPlaylist {

    @TestVisible
    private static Database.SaveResult errorEventResult;
    public static void syncPlaylist(List<ClientCredential__c> credentials) {

        try {
            List<Playlist__c> forInsert = new List<Playlist__c>();
            Map<String, PlaylistTrack__c> playlistTrackMap = new Map<String, PlaylistTrack__c>();

            for (ClientCredential__c cred : credentials) {

                HttpResponse token = SpotifyApiHttpClient.getToken(
                    cred.ClientId__c, 
                    cred.ClientSecret__c
                );

                if (token.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                continue;

                TokenResponse tokenRes = TokenResponse.parse(token.getBody());
                PlaylistResponse playlists;
                Integer cont = 0;

                do {

                    HttpResponse playlistsRes = SpotifyApiHttpClient.getPlaylist(
                        tokenRes.access_token, 
                        cred.SpotifyUserId__c, 
                        cont 
                    );

                    if (playlistsRes.getStatusCode() != SpotifyApiHttpClient.SUCCESS_STATUS_CODE)
                    continue; 

                    playlists = PlaylistResponse.parse(playlistsRes.getBody()
                    .replaceAll('"public" :', '"publicField" :'));

                    for (SimplefiedPlaylistObject playlist : playlists.items) {
                        Integer duration = 0;

                        for (SimplefieldTracksObject track : getPlaylistTrack(tokenRes.access_token, playlist.id)) {

                            duration += track.duration_ms;
                            String key = track.id + playlist.id;
                            PlaylistTrack__c playlistTrackRecord = new PlaylistTrack__c(
                                PlaylistTrack__c = key,
                                Playlist__r = new Playlist__c(SpotifyId__c = playlist.id),
                                Track__r = new Track__c(SpotifyId__c = track.id));
                            playlistTrackMap.put(key, playlistTrackRecord);
                        }

                        Playlist__c record = new Playlist__c(
                            SpotifyId__c = playlist.id,
                            Name = playlist.name,
                            Description__c = playlist.description,
                            Public__c =  playlist.publicField,
                            url__c = playlist.external_urls?.spotify,
                            followers__c = playlist.followers,
                            Duration__c = duration
                        );
                        forInsert.add(record);
                    }
                    cont += playlists.items.size();

                } while (cont < playlists.total);
            }
            if (!forInsert.isEmpty()) {
                upsert forInsert SpotifyId__c;
            }

            upsert playlistTrackMap.values() PlaylistTrack__c;

        } catch (Exception error) {
            Spotify_Request_Log__e errorEvent = new Spotify_Request_Log__e(
                ApexError__c = error.getMessage()
            );
            errorEventResult = EventBus.publish(errorEvent);
        }
    }

    private static List<SimplefieldTracksObject> getPlaylistTrack(String token,String playlistId) {

        List<SimplefieldTracksObject> result = new List<SimplefieldTracksObject>();
        HttpResponse trackRes = SpotifyApiHttpClient.getPlaylistTracks(token, playlistId);

        if (trackRes.getStatusCode() == SpotifyApiHttpClient.SUCCESS_STATUS_CODE) {

            TrackResponse tracks = TrackResponse.parse(trackRes.getBody());
            result.addAll(tracks.getTracks());
        }

        return result;
    }  
}