force-app/main/default/objects/ClientCredential__c/ClientCredential__c.object-meta.xml
<CustomObject>
    <label>Client Credential</label>
    <nameField>
        <label>ClientCredential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientCredential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientCredential__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClientCredential__c/fields/SpotifyUserId__c.field-meta.xml
<CustomField>
    <fullName>SpotifyUserId__c</fullName>
    <label>Spotify User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/jobs/PlaylistBatch.cls
public class PlaylistBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT ClientId__c, ClientSecret__c, SpotifyUserId__c FROM ClientCredential__c]);
    }

    public void execute(Database.BatchableContext bc, List<ClientCredential__c> BatchCred) {
        SyncPlaylists.syncPlaylist(BatchCred);
    }

    public void finish(Database.BatchableContext bc) {}
}