force-app/main/default/objects/log__c/log__c.object-meta.xml
<CustomObject>
    <label>log</label>
    <nameField>
        <label>log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spotify_Request_Log__e/Spotify_Request_Log__e.object-meta.xml
<CustomObject>
    <label>Spotify_Request_Log</label>
    <pluralLabel>Spotify_Request_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Spotify_Request_Log__e/fields/ApexError__c.field-meta.xml
<CustomField>
    <fullName>ApexError__c</fullName>
    <label>ApexError</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SpotifyRequestLogTriggerTest.cls
@isTest
private class SpotifyRequestLogTrigger {
    @isTest static void spotifyRequestLogTrigger() {
        // prepare data
        Spotify_Request_Log__e errorEvent = new Spotify_Request_Log__e(
            ApexError__c = 'error'
		);
        // test
        Test.startTest();
        EventBus.publish(errorEvent);
        Test.stopTest();
        //assert
        List<Log__c> error = [SELECT ApexError__c FROM Log__c WHERE ApexError__c =: errorEvent.ApexError__c];
        Assert.isFalse(error.isEmpty());
    }
}